### ISSUE TITLE
Gamification with NFTs

### ISSUE THREAD

**Issue by Ivshti** [AmbireTech/adex-staking#107]
Create a few card-style art pieces that we'll airdrop as NFTs to users with specific achievements:

- big bonds
- staked for a long time without unbonding
- staked since pre-migration

We'll have a new page where you can claim those NFTs

**Comment by alesinka** [comment]
Here is an example page for claiming the NFTs, which are experimental at this moment - a bit psychedelic probably, but the style and their message could be discussed further with the marketing team, i guess :)
![Claim NFTs](https://user-images.githubusercontent.com/24762344/111987202-9083d680-8b17-11eb-984e-f24b72f4deca.png)

**Comment by Ivshti** [comment]
Those are gorgeous!

**Comment by vanina-iv** [comment]
Love them!!! <3

**Comment by Ivshti** [comment]
@dmngdsm how about "whale hello there" for whales

**Comment by Ivshti** [comment]
Putting this on hold for now cause such efforts would be focused on the Wallet. Will add this to the Wallet projects symbolically until we figure how to adapt it.
