### ISSUE TITLE
New Staking portal bugs 

### ISSUE THREAD

**Issue by Vesi5** [AmbireTech/adex-staking#176]
A few bugs and fixes that need to be done: 

- [x]  When I disconnect my wallet I get this popup. 
<img width="1456" alt="Screenshot 2024-07-04 at 13 56 08" src="https://github.com/AmbireTech/adex-staking/assets/64790881/ce574934-c57d-4e43-aefb-90794d385696">

- [x] Change the logo in the popup above to the new one
- [x] Let's put Tom over Loyalty here
<img width="1457" alt="Screenshot 2024-07-04 at 14 10 00" src="https://github.com/AmbireTech/adex-staking/assets/64790881/1864b537-e7da-4ef3-8dab-2c33f9b7d41b">

- [x] Home page --> The Deposit button on the Loyalty pool should be inactive

**Comment by KristiyanStefanov23** [comment]
- [ ] Bring back X closing button to the Pools STAKE ADX button
- [ ] Input to be active without giving consent and to accept numbers only
- [ ] Rename Tom to "Tom Pool"
- [ ] Remove pool stats from Tom
- [ ] Line up buttons in Pools

**Comment by Vesi5** [comment]
- [ ] add a globe icon next to the language in the upper right corner
- [ ] there is also inconsistency between Terms of service (under Help button) and Terms and conditions (bottom left) - should be Terms and conditions everywhere
- [ ] add a link “Contact us” (URL: https://help.adex.network/hc/en-us/requests/new) under Help in the dropdown menu

**Comment by Vesi5** [comment]
- [ ] The portal shows balance, but is asking to connect wallet at the same time. I connected Ambire Wallet through Wallet Connect before that and it might be because I switched addresses within the wallet.
![Image](https://github.com/user-attachments/assets/66692d6a-e5a8-4405-9ca3-b5dd4955219d)
